Add 'No TODO Without JIRA Ticket' Rule
criteo/eslint-plugin-criteo pull request #10
Opened 2022-06-23 16:43 UTC by joepikowski

2022-06-23 17:31 UTC, benjaminchad requested changes
Thanks! I just have a couple of pedantic points but this is a really great initiative!

2022-06-23 18:21 UTC, joepikowski commented on lib/rules/no-todo-without-ticket.js
> +      return !!text.match(/(^|\s|\/|\/\*)todo([:\s]|$|\*)/gmi);
Oh wow I didn't know about \b  - much more concise, thanks. Agreed about the g flag.

2022-06-23 18:26 UTC, joepikowski commented on lib/rules/no-todo-without-ticket.js
> +      return !!text.match(/(^|\s|\/|\/\*)([A-Z][A-Z0-9]+-[0-9]+)([:\s]|$|\*)/gm);
Sources: [This](https://stackoverflow.com/questions/19322669/regular-expression-for-a-jira-identifier#comment125613082_30518972), which [references a post from Atlassian](https://jira.atlassian.com/browse/JRASERVER-37162?focusedCommentId=699814&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-699814).

2022-06-24 10:42 UTC, benjaminchad approved these changes

2022-06-28 15:39 UTC, merged